server:
  port: 8080
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://database-1.cvwqmag8002v.ap-southeast-1.rds.amazonaws.com:3306/retail-store?createDatabaseIfNotExist=true
    username: admin
    password: admin_091979818
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  output:
    ansi:
      enabled: always
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 86400000 # 1 day
      refresh-token:
        expiration: 604800000 # 1 week
    password: 123456
    url-client: http://localhost:5173
  cloudinary:
    cloud-name: dujylxkra
    api-key: 228233235289595
    api-secret: h7yBSJ0KOHB1Cglz7eCbwig5QXU
